version: '3'

services:
  postgresql:
    image: 'bitnami/postgresql:12'
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql12'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=music_db
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    links:
      - postgresql

volumes:
  postgresql_data:
    driver: local